[pre-commit]
parallel = true

[pre-commit.commands.format-go]
run = "gofmt -s -w {staged_files}"
glob = ["*.go"]
stage_fixed = true

[pre-commit.commands.format-yaml]
run = "yamlfmt {staged_files}"
glob = ["*.yml", "*.yaml"]
stage_fixed = true

[pre-commit.commands.shellcheck]
glob = "*.sh"
run = "shellcheck {staged_files}"
